### ISSUE TITLE
Provide a way to use a single launcher and load a specific application

### ISSUE THREAD

**Issue by otavio** [TotalCross/totalcross#15]
We should have a way to override the default behavior so we can use a single launcher without the need of copying it.

The referred code is:

https://github.com/TotalCross/totalcross/blob/develop/TotalCrossVM/src/launchers/linux/Launcher.c#L1-L10

One suggestion is to use a specific command line or an environment variable (e.g: `APP_NAME`).

**Comment by ItaloYeltsin** [comment]
Hello @otavio ,

Indeed, that's make all the sense for linux arm devices, since embedded devices usually are dedicated to run only one application for one purpose. I don't agree to do this for Linux Desktop since you can have multiple TC applications and depending on the way you set the environment variable this may lead to different Launchers of  distinct application pointing to the wrong app name.

**Comment by otavio** [comment]
Hello @ItaloYeltsin, I disagree.

You could have a single launcher and do:

```
totalcross-run -app app.tcz
```

or

```
TOTALCROSS_APP=app.tcz totalcross-run
```

and so on. This allows for a *single* runtime and VM to be used for multiple applications.

For the Visual Studio Code bundler, you can keep backward compatibility using a Shell Script wrapper as:

```
#/bin/sh

exec ./totalcross-run -app $0.tcz
```

and send it all bundled together.

**Comment by ItaloYeltsin** [comment]
Ok, I got it.
In order to implement this feature, we have to:

- [ ]  provide a totalcross package for debian (this package would contain our Launcher and libtcvm.so, TCFont.tcz TCBase.tcz, and TCUI.tcz; 
- [ ] make the launcher runs the user application passing the argument -app YOUR_APP.tcz;
- [ ] make the our Java api (totalcross-sdk.jar) trough the class Deploy.jar, provide a .sh wrapper that executes `exec ./totalcross-run -app $0.tcz`. That wrapper would have the same name of the application;
- [ ] Update documentation.

**Comment by acmlira** [comment]
Just reopen if you need more attention to this issue, but in this moment our minimum solve is #61. To use this feature, just use the command line:
```bash
./Launcher MyApp
```
