### ISSUE TITLE
Component Radio is shorting text 

### ISSUE THREAD

**Issue by VicMisael** [TotalCross/totalcross#178]
## Issue Title
Component Radio is shorting Text 

## Describe the bug
Radio is wrongly shorting its text when setting preferred width and running it on Android.

## To Reproduce
Open the TCSample application, and go to UI>Camera
It's possible to see the bug there
## Expected behavior
The text should be seen completely
## Screenshots or videos

![image](https://user-images.githubusercontent.com/29692098/97740136-91ac5c80-1abf-11eb-94c3-97201cb452bc.png)

## Devices:
Please complete the following information:
 - Device: Lenovo Vibe K5
 - OS: Android
 - OS Version: 6.0.1
 - TotalCross Version: 6.1.1

**Comment by nmarquesin** [comment]
This seams to be a feature, not a bug. We can improve our documentation to clarify how the feature works. @flsobral any suggestion?

**Comment by teras** [comment]
Indeed this is really a feature. When the content does not fit in the proposed size of the Label widget, it needs to truncate it.

It can't be documented under javadoc since this appears in many widgets and it's a generic behavior.
So, if we want to document it, maybe somewhere generic. But under my point of view, this is common knowledge. When something doesn't fit, needs to be truncated.
