### ISSUE TITLE
New parser fail NoSuchMethodError

### ISSUE THREAD

**Issue by Iaggoq** [TotalCross/totalcross#273]
## Describe the bug
Doing packaged with new version 7.0.0 we get a noSuchMethodError.

## Devices:
Please complete the following information:
 - System OS (name and version): Rasp, Android
 - TotalCross Version: 7.0.0
 

## To Reproduce
Replace in .m2 knowcode 1.13 jar with the attached .jar to use the new enconding form and when creating and open in rasp or android we get that error.

## Screenshots or videos
![unknown](https://user-images.githubusercontent.com/50816129/104943840-1c04ae00-5995-11eb-8c0c-b213952b358b.png)
[1.13.zip](https://github.com/TotalCross/totalcross/files/5831557/1.13.zip)

**Comment by teras** [comment]
To me it looks like a JAR incompatibility. Is it possible to update the JAR with the new API?

**Comment by Iaggoq** [comment]
The jar in maven is old dated but in the attached jar its updated in simulator works but in the linux arm and android dont

**Comment by brunoamuniz** [comment]
the method "tokenize" is available at TotalCross API level but not implemented on the VM

**Comment by brunoamuniz** [comment]
@ricardobna any update on this? =)

**Comment by flsobral** [comment]
XmlTokenizer4D and its native implementation were not updated to use characters instead of bytes, that's why it couldn't find the method tokenize with char[] argument.

I told @ricardobna to drop XmlTokenizer4D entirely and compare the performance. We should probably handle any significant loss of performance at Java level on XmlTokenizer, because the current implementation only handles single byte characters.
