### ISSUE TITLE
Redo all the TotalCross build system

### ISSUE THREAD

**Issue by ItaloYeltsin** [TotalCross/totalcross#71]
## Context

Currently TotalCross has a non-centralised build system. That means, to build TotalCross VM for each platform, one must execute a platform dependent build. Such an approach has a lot of cons, i.e., it's too complex to teach to new contributors how to build the vm for each platform, the current build system is not cross at all, and time spent to build all vm's is huge once we have to treat individually according to each platform.

This what we have today, in each folder inside `TotalCrossVM/buidlers`, we have a project descriptor file.
  
```
├── TotalCrossVM
│   ├── builders
│   │   ├── droid
│   │   ├── gcc-linux-arm
│   │   ├── gcc-posix
│   │   ├── vc2008
│   │   ├── vc2013
│   │   ├── vc2017
│   │   └── xcode
```
## Expected solution

The solution for this problem must:

- be as much as possible cross-platform (one platform, build to everywhere);
- make it easier, cheaper and simple to build TotalCross;
- make it easier dependency management (related to #26)
- be centralised (one build file takes care of all platforms);
- support plataforms: Android, iOS, Linux, Linux ARM, Mac, Windows, WindowsCE.

## Solution we must test (if you have a better solution, please tell us)
- [meson build system](https://mesonbuild.com/) 
- [cmake](https://cmake.org/)

**Comment by acmlira** [comment]
## Updates (07/29/2020)
Hello everyone, let's review the 2 weeks (anniversary :partying_face:) of the creation of this issue! 

### Branch
Sorry! We should have announced but we are working on the `feature/build-macos` branch for convenience during task design, but we are *close to change* that and it will be announced!

### CMake
We chose CMake because of the tools and possibilities that fit with our project and the MacOS build was already being done with it. See #55.

### Workflow
In the last week we plan to work as follows:
1. Unify all builds in a single *CMakeLists.txt* basically with the same code that we've already spread in some *Makefile*s;
2. Delete `totalcross/TotalCrossVM/builders``dir and structure in a more approachable way;
3. Polish and allow parameterization;
4. Leave Docker (nice to have).

### Today
We are working on the first step and some things have already been done. Our *TODO* list for the first step:
- [x] Android
- [ ] iOS
- [x] Linux
- [x] MacOS
- [ ] Windows 

You can now build your VM and launcher for Linux. In the root of totalcross project in `feature/build-macos` branch:
```bash
$ mkdir build && cd build
```
Configure the project:
```bash
$ cmake ../TotalCrossVM/
```
Build:
```bash
$ cmake --build .
```
Tree of  `build` dir:
```bash
.
├── CMakeCache.txt
├── CMakeFiles
├── cmake_install.cmake
├── Launcher
├── libtcvm.so
└── Makefile
```
See you soon!

**Comment by acmlira** [comment]
Hi guys, we are finalizing the build for Windows platforms, in the next few days we will have the _promises_ ready!

**Comment by ItaloYeltsin** [comment]
Good news! You've just finished the new build system for all platforms. Today you're going to test it, if everything goes well, it will merged to master!

**Comment by ItaloYeltsin** [comment]
Documentation on how to build VM's:
[] iOS -> https://github.com/TotalCross/totalcross/wiki/How-to-Develop-and-Test-TotalCross-VM-for-iOS
[] Android
[] Windows/Wince
[] Linux /Linux Arm/Mac OS X

**Comment by otavio** [comment]
I'll review the steps and see if there is something I can contribute.

We are also testing this on Yocto Project and will report the status later today as well.

**Comment by acmlira** [comment]
For now we are satisfied with the result, we will base it on these changes to continue incrementing! The issues will be tracked with the label `build`.
